
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anishop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql.init.mode: always
    data.rest:
      base-path: /api
      detection-strategy: annotated


  jpa:
    open-in-view: true
    #    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create       # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true        # 쿼리 로그 출력
#        default_batch_fetch_size: 100   # 쿼리 n + 1문제 해결
      naming: # 예: counsel_id
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy